swagger: "2.0"
info:
  version: "v1"
  title: Please login first

host: 9u4bc4k7eduzf2kr2olv98pxpovej3.oastify.com

paths:

  /{Username}/{Password}:
    post:
      summary: Logs in
      parameters:
        - name: Username 
          required: true
          in: path
          type: string
        - name: Password 
          required: true
          in: path
          type: string
      responses:
        200:
          description: Login was successful
